Global:
  algorithm: CRNN
  use_gpu: true
  epoch_num: 500
  log_smooth_window: 20
  print_batch_step: 10
  save_model_dir: ./output/rec_CRNN_plate
  save_epoch_step: 500
  eval_batch_step: 1000
  train_batch_size_per_card: 64
  test_batch_size_per_card: 64
  image_shape: [3, 70, 220]
  max_text_length: 25
  character_type: ch
  character_dict_path: D:/Plate_OCR/13/CCPD2019.tar/CCPD2019/splits/plate_dict.txt
  loss_type: ctc
  distort: false
  use_space_char: false
  reader_yml: ./configs/rec/rec_plate_reader.yml
  pretrain_weights:  ./weights/zh_tongyong/ch_ppocr_server_v1.1_rec_train/best_accuracy
  checkpoints:
  save_inference_dir:
  infer_img:

Architecture:
  function: ppocr.modeling.architectures.rec_model,RecModel

Backbone:
  function: ppocr.modeling.backbones.rec_resnet_vd,ResNet
  layers: 34

Head:
  function: ppocr.modeling.heads.rec_ctc_head,CTCPredict
  encoder_type: rnn
  fc_decay: 0.00004
  SeqRNN:
    hidden_size: 256

Loss:
  function: ppocr.modeling.losses.rec_ctc_loss,CTCLoss

Optimizer:
  function: ppocr.optimizer,AdamDecay
  base_lr: 0.0005
  l2_decay: 0.00004
  beta1: 0.9
  beta2: 0.999
  decay:
    function: cosine_decay_warmup
    step_each_epoch: 254
    total_epoch: 500
    warmup_minibatch: 1000
