TrainReader:
  reader_function: ppocr.data.det.dataset_traversal,TrainReader
  process_function: ppocr.data.det.db_process,DBProcessTrain
  num_workers: 8
  img_set_dir: D:/Plate_OCR/13/CCPD2019.tar/CCPD2019/
  label_file_path: D:/Plate_OCR/13/CCPD2019.tar/CCPD2019/splits/det_gt_train_1.txt

EvalReader:
  reader_function: ppocr.data.det.dataset_traversal,EvalTestReader
  process_function: ppocr.data.det.db_process,DBProcessTest
  img_set_dir: D:/Plate_OCR/13/CCPD2019.tar/CCPD2019/
  label_file_path: D:/Plate_OCR/13/CCPD2019.tar/CCPD2019/splits/det_gt_test_1.txt
  test_image_shape: [736, 1280]
  
TestReader:
  reader_function: ppocr.data.det.dataset_traversal,EvalTestReader
  process_function: ppocr.data.det.db_process,DBProcessTest
  infer_img: C:/Users/Administrator/Desktop/test/
  img_set_dir: D:/Plate_OCR/13/CCPD2019.tar/CCPD2019/
  label_file_path: D:/Plate_OCR/13/CCPD2019.tar/CCPD2019/splits/det_gt_test_1.txt
  do_eval: True
